Repository f-lab-edu/home-delivery, pull requests merged in 2022-08, with the labels that each got.

#30 [#25] 캐시 설정, 회원 매장조회, 라이더 출퇴근
  build.gradle
  src/main/java/com/flab/delivery/config/RedisConfig.java
  src/main/java/com/flab/delivery/controller/CategoryController.java
  src/main/java/com/flab/delivery/controller/RiderController.java
  src/main/java/com/flab/delivery/controller/StoreController.java
  src/main/java/com/flab/delivery/dao/RiderDao.java
  src/main/java/com/flab/delivery/dto/category/CategoryDto.java
  src/main/java/com/flab/delivery/dto/store/StoreDto.java
  src/main/java/com/flab/delivery/exception/AbstractException.java
  src/main/java/com/flab/delivery/exception/SessionLoginException.java
  src/main/java/com/flab/delivery/exception/StoreException.java
  src/main/java/com/flab/delivery/mapper/CategoryMapper.java
  src/main/java/com/flab/delivery/mapper/StoreMapper.java
  src/main/java/com/flab/delivery/service/AddressService.java
  src/main/java/com/flab/delivery/service/CategoryService.java
  src/main/java/com/flab/delivery/service/RiderService.java
  src/main/java/com/flab/delivery/service/StoreService.java
  src/main/java/com/flab/delivery/service/StoreServiceImpl.java
  src/main/java/com/flab/delivery/utils/CacheConstants.java
  src/main/resources/application.properties
  src/main/resources/mappers/CategoryMapper.xml
  src/main/resources/mappers/StoreMapper.xml
  src/test/java/com/flab/delivery/AbstractRedisContainer.java
  src/test/java/com/flab/delivery/annotation/IntegrationTest.java
  src/test/java/com/flab/delivery/controller/StoreControllerTest.java
  src/test/java/com/flab/delivery/dao/RiderDaoTestRedis.java
  src/test/java/com/flab/delivery/fixture/CommonTest.java
  src/test/java/com/flab/delivery/fixture/TestDto.java
  src/test/java/com/flab/delivery/integration/AddressIntegrationTest.java
  src/test/java/com/flab/delivery/integration/CategoryIntegrationTest.java
  src/test/java/com/flab/delivery/integration/RiderIntegrationTestRedis.java
  src/test/java/com/flab/delivery/integration/UserIntegrationTest.java
  src/test/java/com/flab/delivery/mapper/CategoryMapperTest.java
  src/test/java/com/flab/delivery/mapper/StoreMapperTest.java
  src/test/java/com/flab/delivery/service/CategoryServiceTest.java
  src/test/java/com/flab/delivery/service/StoreServiceTest.java
  src/test/resources/application.properties
Labels: help wanted, 기능, Need Review

#37 [#33] 장바구니 기능
  src/main/java/com/flab/delivery/config/RedisCartConfig.java
  src/main/java/com/flab/delivery/controller/CartController.java
  src/main/java/com/flab/delivery/dao/CartDao.java
  src/main/java/com/flab/delivery/dto/cart/CartResponseDto.java
  src/main/java/com/flab/delivery/dto/cart/ItemDto.java
  src/main/java/com/flab/delivery/dto/order/OrderMenuDto.java
  src/main/java/com/flab/delivery/enums/OperationType.java
  src/main/java/com/flab/delivery/service/CartService.java
  src/main/resources/application.properties
  src/test/java/com/flab/delivery/AbstractRedisContainer.java
  src/test/java/com/flab/delivery/integration/CartIntegrationTest.java
  src/test/java/com/flab/delivery/service/CartServiceTest.java
  src/test/resources/application.properties
Labels: 기능, Need Review

#39 [#36] 배달 관련 API 구현
  src/main/java/com/flab/delivery/DeliveryApplication.java
  src/main/java/com/flab/delivery/config/RedisCacheConfig.java
  src/main/java/com/flab/delivery/controller/OwnerOrderController.java
  src/main/java/com/flab/delivery/controller/RiderOrderController.java
  src/main/java/com/flab/delivery/controller/UserOrderController.java
  src/main/java/com/flab/delivery/controller/validator/OrderValidator.java
  src/main/java/com/flab/delivery/dao/RiderDao.java
  src/main/java/com/flab/delivery/dto/address/AddressRequestDto.java
  src/main/java/com/flab/delivery/dto/order/OrderDto.java
  src/main/java/com/flab/delivery/dto/order/OrderHistoryDto.java
  src/main/java/com/flab/delivery/dto/order/OrderMenuHistoryDto.java
  src/main/java/com/flab/delivery/dto/order/owner/OwnerOrderResponseDto.java
  src/main/java/com/flab/delivery/dto/order/rider/OrderDeliveryDto.java
  src/main/java/com/flab/delivery/dto/order/user/OrderSimpleResponseDto.java
  src/main/java/com/flab/delivery/dto/user/SignUpDto.java
  src/main/java/com/flab/delivery/exception/handler/OrderExceptionHandler.java
  src/main/java/com/flab/delivery/exception/message/ErrorMessageConstants.java
  src/main/java/com/flab/delivery/mapper/OrderMapper.java
  src/main/java/com/flab/delivery/service/AddressService.java
  src/main/java/com/flab/delivery/service/OwnerOrderService.java
  src/main/java/com/flab/delivery/service/RiderOrderService.java
  src/main/java/com/flab/delivery/service/UserOrderService.java
  src/main/java/com/flab/delivery/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/mappers/OrderMapper.xml
  src/main/resources/mappers/StoreMapper.xml
  src/test/java/com/flab/delivery/dao/RiderDaoTest.java
  src/test/java/com/flab/delivery/dao/RiderDaoTestRedis.java
  src/test/java/com/flab/delivery/fixture/TestDto.java
  src/test/java/com/flab/delivery/integration/OwnerOrderIntegrationTest.java
  src/test/java/com/flab/delivery/integration/RiderOrderIntegrationTest.java
  src/test/java/com/flab/delivery/integration/UserOrderIntegrationTest.java
  src/test/java/com/flab/delivery/mapper/OrderMapperTest.java
  src/test/java/com/flab/delivery/service/OwnerOrderServiceTest.java
  src/test/java/com/flab/delivery/service/RiderOrderServiceTest.java
  src/test/java/com/flab/delivery/service/UserOrderServiceTest.java
Labels: Need Review

#40 [#38] 푸시알림기능, 캐시적용
  build.gradle
  src/main/java/com/flab/delivery/config/AsyncConfig.java
  src/main/java/com/flab/delivery/config/RedisFCMTokenConfig.java
  src/main/java/com/flab/delivery/controller/MenuController.java
  src/main/java/com/flab/delivery/controller/MenuGroupController.java
  src/main/java/com/flab/delivery/controller/UserController.java
  src/main/java/com/flab/delivery/dao/FCMTokenDao.java
  src/main/java/com/flab/delivery/dto/order/OrderMenuDto.java
  src/main/java/com/flab/delivery/dto/user/UserDto.java
  src/main/java/com/flab/delivery/firebase/FCMInitializer.java
  src/main/java/com/flab/delivery/service/FCMService.java
  src/main/java/com/flab/delivery/service/MenuGroupService.java
  src/main/java/com/flab/delivery/service/MenuService.java
  src/main/java/com/flab/delivery/service/OptionService.java
  src/main/java/com/flab/delivery/service/UserOrderService.java
  src/main/java/com/flab/delivery/utils/CacheConstants.java
  src/main/java/com/flab/delivery/utils/FCMAlarmConstants.java
  src/main/resources/application.properties
  src/main/resources/home-delivery-dev-firebase-adminsdk-vfi8k-c08e1e8e22.json
  src/test/java/com/flab/delivery/dao/CartDaoTest.java
  src/test/java/com/flab/delivery/dao/FCMTokenDaoTest.java
  src/test/java/com/flab/delivery/integration/CartIntegrationTest.java
  src/test/java/com/flab/delivery/integration/MenuGroupIntegrationTest.java
  src/test/java/com/flab/delivery/integration/MenuIntegrationTest.java
  src/test/java/com/flab/delivery/integration/UserIntegrationTest.java
  src/test/java/com/flab/delivery/service/FCMServiceTest.java
  src/test/java/com/flab/delivery/service/MenuGroupServiceTest.java
  src/test/java/com/flab/delivery/service/MenuServiceTest.java
  src/test/java/com/flab/delivery/service/UserOrderServiceTest.java
  src/test/resources/application.properties
Labels: 기능, Need Review
